2024-01-02 20:34:00 [   DEBUG] [asyncio] Using proactor: IocpProactor (proactor_events.py:634)
2024-01-02 20:34:10 [    INFO] [test_03_logging] test_a1 (test_03_logging.py:12)
2024-01-02 20:34:10 [    INFO] [test_03_logging] test_a2 (test_03_logging.py:18)
2024-01-02 20:34:10 [    INFO] [test_03_logging] API call done (test_03_logging.py:28)
2024-01-02 20:34:10 [   ERROR] [test_03_logging] test_case03 xfail (test_03_logging.py:41)
2024-01-02 20:34:10 [   ERROR] [test_03_logging] func1 ValueError (test_03_logging.py:33)
2024-01-02 20:34:13 [   DEBUG] [asyncio] Using proactor: IocpProactor (proactor_events.py:634)
2024-01-02 20:35:12 [   DEBUG] [urllib3.connectionpool] Starting new HTTPS connection (1): httpbin.org:443 (connectionpool.py:1053)
2024-01-02 20:35:13 [   DEBUG] [urllib3.connectionpool] https://httpbin.org:443 "GET /digest-auth/auth/123/123/MD5 HTTP/1.1" 401 0 (connectionpool.py:547)
2024-01-02 20:35:13 [   DEBUG] [urllib3.connectionpool] https://httpbin.org:443 "GET /digest-auth/auth/123/123/MD5 HTTP/1.1" 200 46 (connectionpool.py:547)
2024-01-02 20:35:13 [   DEBUG] [urllib3.connectionpool] Starting new HTTPS connection (1): petstore.swagger.io:443 (connectionpool.py:1053)
2024-01-02 20:35:14 [   DEBUG] [urllib3.connectionpool] https://petstore.swagger.io:443 "PUT /v2/pet/ HTTP/1.1" 200 None (connectionpool.py:547)
2024-01-02 20:35:14 [    INFO] [test_pets] API call done (test_pets.py:27)
2024-01-02 20:35:14 [   DEBUG] [urllib3.connectionpool] Starting new HTTPS connection (1): petstore.swagger.io:443 (connectionpool.py:1053)
2024-01-02 20:35:14 [   DEBUG] [urllib3.connectionpool] https://petstore.swagger.io:443 "GET /v2/pet/200 HTTP/1.1" 200 None (connectionpool.py:547)
2024-01-02 20:35:14 [   DEBUG] [urllib3.connectionpool] Starting new HTTPS connection (1): petstore.swagger.io:443 (connectionpool.py:1053)
2024-01-02 20:35:15 [   DEBUG] [urllib3.connectionpool] https://petstore.swagger.io:443 "PUT /v2/pet/ HTTP/1.1" 200 None (connectionpool.py:547)
2024-01-02 20:35:15 [    INFO] [test_pets] API call done (test_pets.py:46)
2024-01-02 20:35:15 [   DEBUG] [urllib3.connectionpool] Starting new HTTPS connection (1): petstore.swagger.io:443 (connectionpool.py:1053)
2024-01-02 20:35:15 [   DEBUG] [urllib3.connectionpool] https://petstore.swagger.io:443 "DELETE /v2/pet/200 HTTP/1.1" 200 None (connectionpool.py:547)
2024-01-02 20:35:18 [   DEBUG] [urllib3.connectionpool] Starting new HTTPS connection (1): petstore.swagger.io:443 (connectionpool.py:1053)
2024-01-02 20:35:19 [   DEBUG] [urllib3.connectionpool] https://petstore.swagger.io:443 "POST /v2/pet HTTP/1.1" 200 None (connectionpool.py:547)
