2023-12-28 17:55:50 [    INFO] [test_03_logging] test_a1 (test_03_logging.py:12)
2023-12-28 17:55:50 [    INFO] [test_03_logging] test_a2 (test_03_logging.py:18)
2023-12-28 17:55:50 [    INFO] [test_03_logging] API call done (test_03_logging.py:28)
2023-12-28 17:55:50 [   ERROR] [test_03_logging] test_case03 xfail (test_03_logging.py:41)
2023-12-28 17:55:50 [   ERROR] [test_03_logging] func1 ValueError (test_03_logging.py:33)
2023-12-28 17:55:53 [   DEBUG] [asyncio] Using proactor: IocpProactor (proactor_events.py:634)
2023-12-28 17:56:45 [   DEBUG] [urllib3.connectionpool] Starting new HTTPS connection (1): httpbin.org:443 (connectionpool.py:1053)
2023-12-28 17:56:46 [   DEBUG] [urllib3.connectionpool] https://httpbin.org:443 "GET /digest-auth/auth/123/123/MD5 HTTP/1.1" 401 0 (connectionpool.py:547)
2023-12-28 17:56:46 [   DEBUG] [urllib3.connectionpool] https://httpbin.org:443 "GET /digest-auth/auth/123/123/MD5 HTTP/1.1" 200 46 (connectionpool.py:547)
2023-12-28 17:56:46 [   DEBUG] [urllib3.connectionpool] Starting new HTTPS connection (1): petstore.swagger.io:443 (connectionpool.py:1053)
2023-12-28 17:56:47 [   DEBUG] [urllib3.connectionpool] https://petstore.swagger.io:443 "PUT /v2/pet/ HTTP/1.1" 200 None (connectionpool.py:547)
2023-12-28 17:56:47 [    INFO] [test_pets] API call done (test_pets.py:27)
2023-12-28 17:56:47 [   DEBUG] [urllib3.connectionpool] Starting new HTTPS connection (1): petstore.swagger.io:443 (connectionpool.py:1053)
2023-12-28 17:56:47 [   DEBUG] [urllib3.connectionpool] https://petstore.swagger.io:443 "GET /v2/pet/200 HTTP/1.1" 200 None (connectionpool.py:547)
2023-12-28 17:56:47 [   DEBUG] [urllib3.connectionpool] Starting new HTTPS connection (1): petstore.swagger.io:443 (connectionpool.py:1053)
2023-12-28 17:56:48 [   DEBUG] [urllib3.connectionpool] https://petstore.swagger.io:443 "PUT /v2/pet/ HTTP/1.1" 200 None (connectionpool.py:547)
2023-12-28 17:56:48 [    INFO] [test_pets] API call done (test_pets.py:46)
2023-12-28 17:56:48 [   DEBUG] [urllib3.connectionpool] Starting new HTTPS connection (1): petstore.swagger.io:443 (connectionpool.py:1053)
2023-12-28 17:56:48 [   DEBUG] [urllib3.connectionpool] https://petstore.swagger.io:443 "DELETE /v2/pet/200 HTTP/1.1" 200 None (connectionpool.py:547)
