2023-12-17 13:15:31 [    INFO] [test_03_logging] test_a1 (test_03_logging.py:12)
2023-12-17 13:15:31 [    INFO] [test_03_logging] test_a2 (test_03_logging.py:18)
2023-12-17 13:15:31 [    INFO] [test_03_logging] API call done (test_03_logging.py:28)
2023-12-17 13:15:31 [   ERROR] [test_03_logging] test_case03 xfail (test_03_logging.py:41)
2023-12-17 13:15:31 [   ERROR] [test_03_logging] func1 ValueError (test_03_logging.py:33)
